// <auto-generated />
using System;
using GestaoReservas.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoReservas.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Andar")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<bool>("PermiteRecursos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Predio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sala")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Locais", (string)null);
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DiasMaximosReserva")
                        .HasColumnType("integer");

                    b.Property<int>("DiasMinimosReserva")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroPatrimonio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("NumeroPatrimonio")
                        .IsUnique();

                    b.ToTable("Recursos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Recurso_DiasMaximos_MaiorIgual_DiasMinimos", "\"DiasMaximosReserva\" >= \"DiasMinimosReserva\"");
                        });
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("DataFinal")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicial")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFinal")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicial")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("LocalId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reserva_DataFinal_MaiorIgual_DataInicial", "\"DataFinal\" > \"DataInicial\" OR (\"DataFinal\" = \"DataInicial\" AND \"HoraFinal\" > \"HoraInicial\")");
                        });
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.ReservaRecurso", b =>
                {
                    b.Property<int>("ReservaId")
                        .HasColumnType("integer");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.HasKey("ReservaId", "RecursoId");

                    b.HasIndex("RecursoId");

                    b.ToTable("ReservaRecursos", (string)null);
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Local", b =>
                {
                    b.HasOne("GestaoReservas.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Locais")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Recurso", b =>
                {
                    b.HasOne("GestaoReservas.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Recursos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("GestaoReservas.Domain.Entities.Local", "Local")
                        .WithMany("Reservas")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestaoReservas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.ReservaRecurso", b =>
                {
                    b.HasOne("GestaoReservas.Domain.Entities.Recurso", "Recurso")
                        .WithMany("ReservaRecursos")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaoReservas.Domain.Entities.Reserva", "Reserva")
                        .WithMany("ReservaRecursos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Locais");

                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Local", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Recurso", b =>
                {
                    b.Navigation("ReservaRecursos");
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Reserva", b =>
                {
                    b.Navigation("ReservaRecursos");
                });

            modelBuilder.Entity("GestaoReservas.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
